- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Deploy Nginx configuration
  template:
    src: epicbook.conf.j2
    dest: /etc/nginx/sites-available/epicbook

- name: Enable site and disable default
  file:
    src: /etc/nginx/sites-available/epicbook
    dest: /etc/nginx/sites-enabled/epicbook
    state: link

- name: Remove default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx
